"""Public API for the greenfield execution domain."""

from qarunner.domain.assignment import Assignment, AssignmentState
from qarunner.domain.attempt import Attempt, AttemptState, FinalizeEvidenceResult
from qarunner.domain.authority import AttemptAuthority, WorkerAuthority
from qarunner.domain.batch import Batch, BatchState
from qarunner.domain.digest import Digest, canonical_digest
from qarunner.domain.errors import (
    ArtifactValidationError,
    AssignmentConflict,
    AttemptUnknownReviewRequired,
    CanonicalizationError,
    DomainValidationError,
    EventConflict,
    EvidenceConflict,
    EvidenceDigestMismatch,
    EvidenceNotReady,
    IdempotencyConflict,
    InvalidTransition,
    StaleFence,
    StaleGeneration,
    UnknownObservationConflict,
    VersionConflict,
    WorkerGenerationConflict,
    WorkerNotClaimable,
)
from qarunner.domain.event import AttemptEvent
from qarunner.domain.evidence import (
    ArtifactClass,
    ArtifactPath,
    EvidenceManifest,
    EvidenceProposal,
    EvidenceRequirements,
    PlatformExitClass,
    TrustedExitFacts,
    ValidatedCaseSummary,
    VerifiedArtifact,
    build_evidence_manifest,
)
from qarunner.domain.idempotency import IdempotencyRecord, IdempotencyResolution
from qarunner.domain.manifest import (
    BoundShardPlan,
    CaseManifest,
    EstimateConfidence,
    FrameworkLocator,
    ManifestConstraints,
    ManifestInputs,
    ManifestItem,
    PlannedShard,
    RunBinding,
    ShardPlan,
    ShardRequirements,
    WorkEstimate,
)
from qarunner.domain.run import Run, RunState
from qarunner.domain.unknown import UnknownObservation, UnknownReason, UnknownSource
from qarunner.domain.worker import (
    WORKER_TERMINAL_STATES,
    WORKER_TRANSITIONS,
    ReconcileWorkerFacts,
    WorkerGeneration,
    WorkerRef,
    WorkerState,
)

__all__ = [
    "Attempt",
    "AttemptEvent",
    "AttemptAuthority",
    "AttemptState",
    "Assignment",
    "AssignmentConflict",
    "AssignmentState",
    "AttemptUnknownReviewRequired",
    "ArtifactClass",
    "ArtifactPath",
    "ArtifactValidationError",
    "Batch",
    "BatchState",
    "BoundShardPlan",
    "CanonicalizationError",
    "CaseManifest",
    "Digest",
    "DomainValidationError",
    "EventConflict",
    "EvidenceConflict",
    "EvidenceDigestMismatch",
    "EvidenceManifest",
    "EvidenceNotReady",
    "EvidenceProposal",
    "EvidenceRequirements",
    "EstimateConfidence",
    "FinalizeEvidenceResult",
    "FrameworkLocator",
    "IdempotencyConflict",
    "InvalidTransition",
    "IdempotencyRecord",
    "IdempotencyResolution",
    "ManifestConstraints",
    "ManifestInputs",
    "ManifestItem",
    "PlannedShard",
    "Run",
    "RunState",
    "RunBinding",
    "ReconcileWorkerFacts",
    "PlatformExitClass",
    "StaleFence",
    "StaleGeneration",
    "ShardPlan",
    "ShardRequirements",
    "VersionConflict",
    "TrustedExitFacts",
    "UnknownObservation",
    "UnknownObservationConflict",
    "UnknownReason",
    "UnknownSource",
    "ValidatedCaseSummary",
    "VerifiedArtifact",
    "WORKER_TERMINAL_STATES",
    "WORKER_TRANSITIONS",
    "WorkerGeneration",
    "WorkerGenerationConflict",
    "WorkerNotClaimable",
    "WorkerRef",
    "WorkerState",
    "WorkEstimate",
    "WorkerAuthority",
    "canonical_digest",
    "build_evidence_manifest",
]
