"""Application-facing ports for the greenfield control plane."""

from qarunner.application.ports.audit import AuditLog, AuditRecord
from qarunner.application.ports.batch_finalization import (
    BatchFinalizationGateway,
    BatchFinalizationMutationSnapshot,
    BatchFinalizationProjection,
    BatchFinalizationPublication,
    BatchFinalizationSideEffect,
    BatchFinalizationSourceSnapshot,
    FinalizeBatchAuthority,
)
from qarunner.application.ports.batch_finalization_readiness import (
    AttemptCreationOpportunity,
    AttemptCreationOpportunityKind,
    BatchFinalizationReadinessAuthority,
    BatchFinalizationReadinessGateway,
    BatchFinalizationReadinessMutationSnapshot,
    BatchFinalizationReadinessProjection,
    BatchFinalizationReadinessPublication,
    BatchFinalizationReadinessReason,
    BatchFinalizationReadinessSideEffect,
    BatchFinalizationReadinessSnapshot,
    BatchRunClosure,
    FrozenBoundShardPlan,
)
from qarunner.application.ports.batch_preexecution import (
    AuthorityPermissionDenied,
    AuthorityProjectionStamp,
    AuthorityProjectionUnavailable,
    AuthorityStateConflict,
    BatchCancellationAuthority,
    BatchCancellationSideEffect,
    BatchClosureAuthority,
    BatchClosureSideEffect,
    BatchPreexecutionGateway,
    BatchRejectionAuthority,
    BatchRejectionSideEffect,
)
from qarunner.application.ports.clock import UtcClock
from qarunner.application.ports.common import PortContractError, ReplayResult
from qarunner.application.ports.evidence import (
    EvidenceManifestIndex,
    EvidenceVerificationRequest,
    EvidenceVerifier,
    VerifiedEvidenceInputs,
)
from qarunner.application.ports.execution import (
    ExecutionStopControl,
    ExecutionStopReceipt,
    ExecutionStopRequest,
)
from qarunner.application.ports.facts import (
    AttemptEventLog,
    FactCommitResult,
    FactKey,
    VersionedFactCommand,
    VersionedFactStore,
)
from qarunner.application.ports.handoff import (
    HandoffDeliveryMetadata,
    HandoffEventBlocked,
    HandoffEventConflict,
    HandoffPoisonAlert,
    MaterializedScopeHandoffConsumer,
)
from qarunner.application.ports.ids import OpaqueIdGenerator
from qarunner.application.ports.preexecution_proof import (
    ExecutionChildInventory,
    PreexecutionProofGateway,
    PreexecutionTaskGeneration,
    PreexecutionTaskKey,
    SealedPlannedScopeInventory,
    SealedTaskInventory,
    TaskLedgerPosition,
    TrustedTaskStop,
    ZeroChildSnapshotInputs,
    canonical_task_set_digest,
)
from qarunner.application.ports.retry_commit_start import (
    RetryCommitMutationSnapshot,
    RetryCommitPublication,
    RetryCommitSideEffect,
    RetryCommitStartGateway,
    StoredRetryCommit,
)
from qarunner.application.ports.run_closed_handoff import (
    RunClosedDeliveryMetadata,
    RunClosedFactProvider,
    RunClosedHandoffBlocked,
    RunClosedHandoffConflict,
    RunClosedHandoffConsumer,
    RunClosedPoisonAlert,
)
from qarunner.application.ports.run_finalization import (
    FinalizeRunAuthority,
    RunFinalizationGateway,
    RunFinalizationMutationSnapshot,
    RunFinalizationProjection,
    RunFinalizationPublication,
    RunFinalizationSideEffect,
)
from qarunner.application.ports.run_retry import (
    RetryBudgetReservation,
    RetryQueuePublicationResult,
    RetryQueueReceipt,
    RunRetryGateway,
    RunRetryMutationSnapshot,
    RunRetryProjection,
    RunRetryPublication,
    RunRetrySideEffect,
    RunRetryWriteAuthority,
    UnknownRetryMutationBinding,
    UnknownRetryMutationSnapshot,
    UnknownRetryPublication,
    UnknownRetryWriteAuthority,
)
from qarunner.application.ports.secrets import (
    SecretBroker,
    SecretDeliveryLease,
    SecretRequest,
)
from qarunner.application.ports.transactions import ApplicationUnitOfWork

__all__ = [
    "ApplicationUnitOfWork",
    "AttemptEventLog",
    "AuthorityPermissionDenied",
    "AuthorityProjectionUnavailable",
    "AuthorityProjectionStamp",
    "AuthorityStateConflict",
    "AuditLog",
    "AuditRecord",
    "BatchCancellationAuthority",
    "BatchCancellationSideEffect",
    "BatchClosureSideEffect",
    "BatchClosureAuthority",
    "BatchPreexecutionGateway",
    "BatchFinalizationGateway",
    "BatchFinalizationMutationSnapshot",
    "BatchFinalizationProjection",
    "BatchFinalizationPublication",
    "BatchFinalizationSideEffect",
    "BatchFinalizationSourceSnapshot",
    "AttemptCreationOpportunity",
    "AttemptCreationOpportunityKind",
    "BatchFinalizationReadinessAuthority",
    "BatchFinalizationReadinessGateway",
    "BatchFinalizationReadinessMutationSnapshot",
    "BatchFinalizationReadinessProjection",
    "BatchFinalizationReadinessPublication",
    "BatchFinalizationReadinessReason",
    "BatchFinalizationReadinessSideEffect",
    "BatchFinalizationReadinessSnapshot",
    "BatchRunClosure",
    "FrozenBoundShardPlan",
    "BatchRejectionAuthority",
    "BatchRejectionSideEffect",
    "EvidenceManifestIndex",
    "EvidenceVerificationRequest",
    "EvidenceVerifier",
    "ExecutionStopControl",
    "ExecutionStopReceipt",
    "ExecutionStopRequest",
    "ExecutionChildInventory",
    "FactCommitResult",
    "FactKey",
    "FinalizeRunAuthority",
    "FinalizeBatchAuthority",
    "HandoffEventBlocked",
    "HandoffDeliveryMetadata",
    "HandoffEventConflict",
    "HandoffPoisonAlert",
    "MaterializedScopeHandoffConsumer",
    "OpaqueIdGenerator",
    "PortContractError",
    "PreexecutionProofGateway",
    "PreexecutionTaskGeneration",
    "PreexecutionTaskKey",
    "ReplayResult",
    "RetryCommitMutationSnapshot",
    "RetryCommitPublication",
    "RetryCommitSideEffect",
    "RetryCommitStartGateway",
    "RetryQueuePublicationResult",
    "RetryQueueReceipt",
    "StoredRetryCommit",
    "RunFinalizationGateway",
    "RunFinalizationMutationSnapshot",
    "RunFinalizationProjection",
    "RunFinalizationPublication",
    "RunFinalizationSideEffect",
    "RunClosedFactProvider",
    "RunClosedDeliveryMetadata",
    "RunClosedHandoffBlocked",
    "RunClosedHandoffConflict",
    "RunClosedHandoffConsumer",
    "RunClosedPoisonAlert",
    "RetryBudgetReservation",
    "RunRetryGateway",
    "RunRetryMutationSnapshot",
    "RunRetryProjection",
    "RunRetryPublication",
    "RunRetrySideEffect",
    "RunRetryWriteAuthority",
    "UnknownRetryMutationBinding",
    "UnknownRetryMutationSnapshot",
    "UnknownRetryPublication",
    "UnknownRetryWriteAuthority",
    "SecretBroker",
    "SecretDeliveryLease",
    "SecretRequest",
    "SealedTaskInventory",
    "SealedPlannedScopeInventory",
    "TaskLedgerPosition",
    "UtcClock",
    "TrustedTaskStop",
    "VerifiedEvidenceInputs",
    "VersionedFactCommand",
    "VersionedFactStore",
    "ZeroChildSnapshotInputs",
    "canonical_task_set_digest",
]
