"""T-M0-PORT-001 package-level application port facade."""

from qarunner.application.ports import (
    ApplicationUnitOfWork,
    AttemptEventLog,
    AuditLog,
    AuditRecord,
    AuthorityPermissionDenied,
    AuthorityProjectionUnavailable,
    BatchCancellationAuthority,
    BatchCancellationSideEffect,
    BatchClosureAuthority,
    BatchClosureSideEffect,
    BatchPreexecutionGateway,
    EvidenceManifestIndex,
    EvidenceVerificationRequest,
    EvidenceVerifier,
    ExecutionChildInventory,
    ExecutionStopControl,
    ExecutionStopReceipt,
    ExecutionStopRequest,
    FactCommitResult,
    FactKey,
    OpaqueIdGenerator,
    PortContractError,
    PreexecutionProofGateway,
    PreexecutionTaskGeneration,
    PreexecutionTaskKey,
    ReplayResult,
    SealedTaskInventory,
    SecretBroker,
    SecretDeliveryLease,
    SecretRequest,
    TaskLedgerPosition,
    TrustedTaskStop,
    UtcClock,
    VerifiedEvidenceInputs,
    VersionedFactCommand,
    VersionedFactStore,
    ZeroChildSnapshotInputs,
    canonical_task_set_digest,
)


def test_application_ports_are_available_from_the_public_facade() -> None:
    exported_ports = (
        ApplicationUnitOfWork,
        AttemptEventLog,
        AuthorityPermissionDenied,
        AuthorityProjectionUnavailable,
        AuditLog,
        AuditRecord,
        BatchCancellationAuthority,
        BatchCancellationSideEffect,
        BatchClosureSideEffect,
        BatchClosureAuthority,
        BatchPreexecutionGateway,
        EvidenceManifestIndex,
        EvidenceVerificationRequest,
        EvidenceVerifier,
        ExecutionChildInventory,
        ExecutionStopControl,
        ExecutionStopReceipt,
        ExecutionStopRequest,
        FactCommitResult,
        FactKey,
        OpaqueIdGenerator,
        PortContractError,
        PreexecutionProofGateway,
        PreexecutionTaskGeneration,
        PreexecutionTaskKey,
        ReplayResult,
        SealedTaskInventory,
        SecretBroker,
        SecretDeliveryLease,
        SecretRequest,
        UtcClock,
        TrustedTaskStop,
        TaskLedgerPosition,
        VerifiedEvidenceInputs,
        VersionedFactCommand,
        VersionedFactStore,
        ZeroChildSnapshotInputs,
        canonical_task_set_digest,
    )

    assert all(
        exported_port.__module__.startswith("qarunner.application.ports")
        for exported_port in exported_ports
    )
